import { z } from "zod";

export const DES_DIMENSIONS = [
  "Decision Clarity",
  "Information Relevance",
  "Information Hierarchy",
  "Decision Confidence",
  "Actionability",
] as const;

export const DESDimensionSchema = z.object({
  dimension: z.enum(DES_DIMENSIONS),

  score: z
    .number()
    .int()
    .min(0)
    .max(20),

  reasoning: z
    .string()
    .min(20)
    .max(500),

  supportingEvidence: z
    .array(z.string().min(1))
    .min(1),
});

export const DESDimensionsResponseSchema = z
  .object({
    dimensions: z
      .array(DESDimensionSchema)
      .length(5),
  })
  .superRefine((data, ctx) => {
    const dimensions = data.dimensions.map(
      (item) => item.dimension
    );

    const uniqueDimensions = new Set(dimensions);

    if (uniqueDimensions.size !== 5) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["dimensions"],
        message:
          "DES dimensions must contain exactly one of each dimension.",
      });
    }

    const missingDimensions = DES_DIMENSIONS.filter(
      (dimension) =>
        !dimensions.includes(dimension)
    );

    if (missingDimensions.length > 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["dimensions"],
        message:
          `Missing DES dimensions: ${missingDimensions.join(", ")}`,
      });
    }
  });

export type DESDimension = z.infer<
  typeof DESDimensionSchema
>;

export type DESDimensionsResponse = z.infer<
  typeof DESDimensionsResponseSchema
>;

/**
 * Final DES object used by the product/report.
 *
 * The score and label are calculated by application code,
 * not generated by the AI.
 */
export const DESSchema = z.object({
  score: z
    .number()
    .int()
    .min(0)
    .max(100),

  label: z.enum([
    "Excellent",
    "Good",
    "Needs Attention",
    "Weak",
    "Critical",
  ]),

  dimensions: z
    .array(DESDimensionSchema)
    .length(5),
});

export type DES = z.infer<
  typeof DESSchema
>;